site:
  name: 'Imobiliária Saber'
  site: 'https://saber.imb.br'
  base: '/'
  trailingSlash: false

apps:
  blog:
    isEnabled: true
    pathname: 'blog'
    postsPerPage: 200
    
    post:
      permalink: '/blog/%slug%'
    
    category:
      disabled: false
      permalink: '/blog/category/%slug%'
      
    tag:
      disabled: false
      permalink: '/blog/tag/%slug%'