site:
  name: 'Imobiliária Saber'
  site: 'https://saber.imb.br/blog'
  base: '/'
  trailingSlash: false

apps:
blog:
  isBlogEnabled: true
  postsPerPage: 6
  
  post:
    permalink: '/blog/%slug%'
  
  category:
    disabled: false
    permalink: '/category/%slug%'
    
  tag:
    disabled: false
    permalink: '/tag/%slug%'