site:
  name: 'Imobiliária Saber'
  site: 'https://saber.imb.br/blog'
  base: '/'
  trailingSlash: false

apps:
blog:
  isEnabled: true
  pathname: 'blog'
  postsPerPage: 200
  
  post:
    permalink: '/%slug%'
  
  category:
    disabled: false
    permalink: '/category/%slug%'
    
  tag:
    disabled: false
    permalink: '/tag/%slug%'